name = "kompass-analytics"
main = "index.mjs"
compatibility_date = "2026-08-01"

# ADMIN_TOKEN wird NICHT hier eingetragen, sondern als Secret gesetzt:
#   npx wrangler secret put ADMIN_TOKEN

[[kv_namespaces]]
binding = "PAGEVIEWS"
id = "0c50659a34ae4d638ae770b289477d52"
